package edu.utfpr.ct.localization;

public class ClientLocalizationKeys {
    public static final String FLAG_PATH = "WEB-FLAG-PATH";
    public static final String LANG_ID = "WEB-LANG-IDENTIFIER";
    
    public static final String COMMON_CURRENT_LANGUAGE_TOOLTIP = "COMMON-CURRENT-LANGUAGE-TOOLTIP";
    public static final String COMMON_RETURN_TEXT = "COMMON-RETURN-TEXT";
    public static final String COMMON_RETURN_TOOLTIP = "COMMON-RETURN-TOOLTIP";
    public static final String COMMON_LOGOUT_TOOLTIP = "COMMON-LOGOUT-TOOLTIP";
    
    public static final String CHECKIN_TITLE = "CHECKIN-CARD-GAMENAME";
    public static final String CHECKIN_TEXT_LABEL = "CHECKIN-TEXT-LABEL";
    public static final String CHECKIN_TEXT_ERROR = "CHECKIN-TEXT-ERROR";
    public static final String CHECKIN_WARNING = "CHECKIN-TEXT-WARNING";
    public static final String CHECKIN_SUBMIT = "CHECKIN-ENTER-BUTTON";
    public static final String CHECKIN_INPUT_TOOLTIP = "CHECKIN-INPUT-TOOLTIP";
    public static final String CHECKIN_BUTTON_TOOLTIP = "CHECKIN-BUTTON-TOOLTIP";
    
    public static final String CHOOSE_SUBMIT = "CHOOSE-ENTER-BUTTON";
    public static final String CHOOSE_PW_TEXT = "CHOOSE-PASSWORD-TEXT";
    public static final String CHOOSE_PW_LABEL = "CHOOSE-PASSWORD-LABEL";
    public static final String CHOOSE_PW_WARNING = "CHOOSE-PASSWORD-WARNING";
    public static final String CHOOSE_PW_ENTER = "CHOOSE-PASSWORD-ENTER";
    public static final String CHOOSE_PW_CLOSE = "CHOOSE-PASSWORD-CLOSE";
    public static final String CHOOSE_GAME_TOOLTIP = "CHOOSE-GAMEROOM-TOOLTIP";
    public static final String CHOOSE_REPO_TOOLTIP = "CHOOSE-REPORTROOM-TOOLTIP";
    public static final String CHOOSE_PASSW_INP_TOOLTIP = "CHOOSE-PASSWORD-INPUT-TOOLTIP";
    public static final String CHOOSE_PASSW_CALL_TOOLTIP = "CHOOSE-PASSWORD-BUTTON-ENTER-TOOLTIP";
    public static final String CHOOSE_PASSW_CANCEL_TOOLTIP = "CHOOSE-PASSWORD-BUTTON-CANCEL-TOOLTIP";
    
    public static final String WAIT_TITLE = "WAIT-TITLE";
    public static final String WAIT_RET_TOOLTIP = "WAIT-RETAILER-TOOLTIP";
    public static final String WAIT_WHO_TOOLTIP = "WAIT-WHOLESALER-TOOLTIP";
    public static final String WAIT_DIS_TOOLTIP = "WAIT-DISTRIBUTOR-TOOLTIP";
    public static final String WAIT_PRO_TOOLTIP = "WAIT-PRODUCER-TOOLTIP";

    public static final String GAME_INFO_WEEKS = "GAME-INFO-WEEKS";
    public static final String GAME_INFO_RET = "GAME-INFO-RETAILER";
    public static final String GAME_INFO_WHO = "GAME-INFO-WHOLESALER";
    public static final String GAME_INFO_DIS = "GAME-INFO-DISTRIBUTOR";
    public static final String GAME_INFO_PRO = "GAME-INFO-PRODUCER";
    public static final String GAME_NAME_LABEL = "GAME-NAME-LABEL";
    public static final String GAME_COST_LABEL = "GAME-COST-LABEL";
    public static final String GAME_STOCK_LABEL = "GAME-STOCK-LABEL";
    public static final String GAME_DEBT_LABEL = "GAME-DEBT-LABEL";
    public static final String GAME_LAST_REQUEST_LABEL = "GAME-LAST-REQUEST-LABEL";
    public static final String GAME_INCOMING_HEADER = "GAME-INCOMING-HEADER-LABEL";
    public static final String GAME_INCOMING_HEADER_PRODUCER = "GAME-INCOMING-HEADER-PRODUCER-LABEL";
    public static final String GAME_INCOMING_WEEK_INIT = "GAME-INCOMING-WEEK-LABEL-INIT";
    public static final String GAME_INCOMING_WEEK_END = "GAME-INCOMING-WEEK-LABEL-END";
    public static final String GAME_TABLE_NAME = "GAME-TABLE-NAME";
    public static final String GAME_TABLE_FUNC = "GAME-TABLE-FUNCTION";
    public static final String GAME_TABLE_WEEK = "GAME-TABLE-WEEK";
    public static final String GAME_TABLE_ISTOCK = "GAME-TABLE-INITIAL-STOCK";
    public static final String GAME_TABLE_RECORDER = "GAME-TABLE-RECEIVED-ORDER";
    public static final String GAME_TABLE_PREVPENDING = "GAME-TABLE-PREVIOUSLY-PENDING-ORDERS";
    public static final String GAME_TABLE_EXPECDELIV = "GAME-TABLE-EXPECTED-DELIVERY";
    public static final String GAME_TABLE_ACTUDELI = "GAME-TABLE-ACTUAL-DELIVERY";
    public static final String GAME_TABLE_UNFULFORDER = "GAME-TABLE-UNFULFILLED-ORDER-THIS-WEEK";
    public static final String GAME_TABLE_UNFULFORDER_RETAILER = "GAME-TABLE-UNFULFILLED-ORDER-THIS-WEEK-RETAILER";
    public static final String GAME_TABLE_FSTOCK = "GAME-TABLE-FINAL-STOCK";
    public static final String GAME_TABLE_CONFIRDELI = "GAME-TABLE-CONFIRMED-DELIVERY";
    public static final String GAME_TABLE_COSTDELI = "GAME-TABLE-COST-MISSING-DELIVERY";
    public static final String GAME_TABLE_COSTSTOCK = "GAME-TABLE-COST-STOCKING";
    public static final String GAME_TABLE_PROFSALE = "GAME-TABLE-PROFIT-SALE";
    public static final String GAME_TABLE_TCOST = "GAME-TABLE-TOTAL-COST";
    public static final String GAME_TABLE_BALANCE = "GAME-TABLE-BALANCE";
    public static final String GAME_TABLE_INCORDER = "GAME-TABLE-INCOMMINGORDER";
    public static final String GAME_TABLE_INCORDER_PRODUCER = "GAME-TABLE-INCOMMINGORDER-PRODUCER";
    public static final String GAME_TABLE_REQUEST = "GAME-TABLE-REQUEST";
    public static final String GAME_TABLE_FUNC_CON = "GAME-TABLE-FUNC-CONSUMER";
    public static final String GAME_TABLE_FUNC_RET = "GAME-TABLE-FUNC-RETAILER";
    public static final String GAME_TABLE_FUNC_WHO = "GAME-TABLE-FUNC-WHOLESALER";
    public static final String GAME_TABLE_FUNC_DIS = "GAME-TABLE-FUNC-DISTRIBUTOR";
    public static final String GAME_TABLE_FUNC_PRO = "GAME-TABLE-FUNC-PRODUCER";
    public static final String GAME_CONTROL_LABEL_ALLOW = "GAME-CONTROL-LABEL-ALLOW";
    public static final String GAME_CONTROL_LABEL_BLOCK = "GAME-CONTROL-LABEL-BLOCK";
    public static final String GAME_CONTROL_BUTTON = "GAME-CONTROL-BUTTON";
    public static final String GAME_CONTROL_ERROR = "GAME-CONTROL-ERROR";
    public static final String PLAY_ORDER_INPUT_TOOLTIP = "GAME-CONTROL-INPUT-TOOLTIP";
    public static final String PLAY_ORDER_BUTTON_TOOLTIP = "GAME-CONTROL-BUTTON-TOOLTIP";

    public static final String REPORT_INFO_NAME = "REPORT-INFO-NAME";
    public static final String REPORT_INFO_TYPE = "REPORT-INFO-TYPE";
    public static final String REPORT_TYPE_INFO = "REPORT-TYPE-INFORMED";
    public static final String REPORT_TYPE_NINF = "REPORT-TYPE-NOTINFORMED";
    public static final String REPORT_INFO_STOCKCOST = "REPORT-INFO-STOCKCOST";
    public static final String REPORT_INFO_MISSCOST = "REPORT-INFO-MISSINGCOST";
    public static final String REPORT_INFO_SALEPROFIT = "REPORT-INFO-SALEPROFIT";
    public static final String REPORT_INFO_DELDELAY = "REPORT-INFO-DELIVERYDELAY";
    public static final String REPORT_INFO_INFDURATION = "REPORT-INFO-INFDURATION";
    public static final String REPORT_INFO_REALDURATION = "REPORT-INFO-REALDURATION";
    public static final String REPORT_INFO_RETAILER = "REPORT-INFO-RETAILER";
    public static final String REPORT_INFO_WHOLESALER = "REPORT-INFO-WHOLESALER";
    public static final String REPORT_INFO_DISTRIBUTOR = "REPORT-INFO-DISTRIBUTOR";
    public static final String REPORT_INFO_PRODUCER = "REPORT-INFO-PRODUCER";
    public static final String REPORT_NAME_LABEL = "REPORT-NAME-LABEL";
    public static final String REPORT_COST_LABEL = "REPORT-COST-LABEL";
    public static final String REPORT_STOCK_LABEL = "REPORT-STOCK-LABEL";
        
    public static String CHART_OR_TITLE = "CHART-ORDER-TITLE";
    public static String CHART_OR_LABEL_X = "CHART-ORDER-LABEL-X-AXIS";
    public static String CHART_OR_LABEL_Y = "CHART-ORDER-LABEL-Y-AXIS";
    public static String CHART_OR_FUNCTION_AX = "CHART-ORDER-FUNCTION-";
    public static String CHART_OR_FUNCTION_0 = "CHART-ORDER-FUNCTION-0";
    public static String CHART_OR_FUNCTION_1 = "CHART-ORDER-FUNCTION-1";
    public static String CHART_OR_FUNCTION_2 = "CHART-ORDER-FUNCTION-2";
    public static String CHART_OR_FUNCTION_3 = "CHART-ORDER-FUNCTION-3";
    public static String CHART_OR_FUNCTION_4 = "CHART-ORDER-FUNCTION-4";

    public static String CHART_ST_TITLE = "CHART-STOCK-TITLE";
    public static String CHART_ST_LABEL_X = "CHART-STOCK-LABEL-X-AXIS";
    public static String CHART_ST_LABEL_Y = "CHART-STOCK-LABEL-Y-AXIS";
    public static String CHART_ST_FUNCTION_AX = "CHART-STOCK-FUNCTION-";
    public static String CHART_ST_FUNCTION_0 = "CHART-STOCK-FUNCTION-0";
    public static String CHART_ST_FUNCTION_1 = "CHART-STOCK-FUNCTION-1";
    public static String CHART_ST_FUNCTION_2 = "CHART-STOCK-FUNCTION-2";
    public static String CHART_ST_FUNCTION_3 = "CHART-STOCK-FUNCTION-3";
    public static String CHART_ST_FUNCTION_4 = "CHART-STOCK-FUNCTION-4";
}
