package edu.utfpr.ct.localization;

public class HostLocalizationKeys
{
	public static final String LANGUAGE_NAME = "HOST-LANG-IDENTIFIER";
	public static final String LANGUAGE_FLAG = "HOST-FLAG-PATH";
        
	public static final String FRAME_NAME = "GUI-FRAME-NAME";

	public static final String LABEL_STARTING_WAIT = "GUI-LABEL-AWAIT-START";
	public static final String LABEL_CREATEGAME_NAME = "GUI-LABEL-CREATEGAME-NAME";
	public static final String LABEL_CREATEGAME_PASSWORD_FIELD = "GUI-LABEL-CREATEGAME-PASSWORD-FIELD";
	public static final String LABEL_CREATEGAME_PASSWORD_CHECK = "GUI-LABEL-CREATEGAME-PASSWORD-CHECK";
	public static final String LABEL_CREATEGAME_MISSINGUC = "GUI-LABEL-CREATEGAME-MISSING-UNIT-COST";
	public static final String LABEL_CREATEGAME_STOCKUC = "GUI-LABEL-CREATEGAME-STOCK-UNIT-COST";
	public static final String LABEL_CREATEGAME_SELLINGP = "GUI-LABEL-CREATEGAME-SELLING-PROFFIT";
	public static final String LABEL_CREATEGAME_REAL_DURATION = "GUI-LABEL-CREATEGAME-REAL-DURATION";
	public static final String LABEL_CREATEGAME_INF_DURATION = "GUI-LABEL-CREATEGAME-INFORMED-DURATION";
	public static final String LABEL_CREATEGAME_DEMAND = "GUI-LABEL-CREATEGAME-DEMAND";
	public static final String LABEL_CREATEGAME_INFORMED_SC = "GUI-LABEL-CREATEGAME-INFORMED_SUPPLYCHAIN";
	public static final String LABEL_CREATEGAME_DELIVERY_DELAY = "GUI-LABEL-CREATEGAME-DELIVERY-DELAY";
	public static final String LABEL_CREATEGAME_INITIAL_STOCK = "GUI-LABEL-CREATEGAME-INITIAL-STOCK";

	public static final String TITLE_CREATEGAME_SECURITY_BORDER = "GUI-TITLE-CREATEGAME-SECURITY-BORDER";
	public static final String TITLE_CREATEGAME_DEMAND_BORDER = "GUI-TITLE-CREATEGAME-DEMAND-BORDER";
	public static final String TITLE_CREATEGAME_COSTS_BORDER = "GUI-TITLE-CREATEGAME-COSTS-BORDER";
	public static final String TITLE_CREATEGAME_DURATION_BORDER = "GUI-TITLE-CREATEGAME-DURATION-BORDER";
	public static final String TITLE_CREATEGAME_SUPPLYCHAIN_BORDER = "GUI-TITLE-CREATEGAME-SUPPLYCHAIN-BORDER";

	public static final String MESSAGE_CREATEGAME_WARN_TITLE = "GUI-WARNING-CREATEGAME-FAILED";
	public static final String MESSAGE_CREATEGAME_WARN_FAIL = "GUI-WARNING-CREATEGAME-FAILED-TITLE";
	public static final String MESSAGE_STOPGAME_WARN_TITLE = "GUI-WARNING-STOPGAME-TITLE";
	public static final String MESSAGE_STOPGAME_WARN = "GUI-WARNING-STOPGAME";
	public static final String MESSAGE_CLOSEAPP_WARN_TITLE = "GUI-WARNING-CLOSEAPPLICATION-TITLE";
	public static final String MESSAGE_CLOSEAPP_WARN = "GUI-WARNING-CLOSEAPPLICATION";
	public static final String MESSAGE_DELETE_GAME_WARN_BEG = "GUI-WARNING-DELETE-GAME-BEGIN";
	public static final String MESSAGE_DELETE_GAME_WARN_END = "GUI-WARNING-DELETE-GAME-END";
	public static final String MESSAGE_DELETE_GAME_WARN_TITLE_BEG = "GUI-WARNING-DELETE-GAME-TITLE-BEGIN";
	public static final String MESSAGE_DELETE_GAME_WARN_TITLE_END = "GUI-WARNING-DELETE-GAME-TITLE-END";
	public static final String MESSAGE_DELETE_REPO_WARN_BEG = "GUI-WARNING-DELETE-REPORT-BEGIN";
	public static final String MESSAGE_DELETE_REPO_WARN_END = "GUI-WARNING-DELETE-REPORT-END";
	public static final String MESSAGE_DELETE_REPO_WARN_TITLE_BEG = "GUI-WARNING-DELETE-REPORT-TITLE-BEGIN";
	public static final String MESSAGE_DELETE_REPO_WARN_TITLE_END = "GUI-WARNING-DELETE-REPORT-TITLE-END";

	public static final String HOME_ICON = "GUI-ICON-HOME-TAB";
	public static final String PLUS_ICON = "GUI-ICON-PLUS-TAB";
	public static final String RELOAD_ICON = "GUI-ICON-RELOAD-BUTTON";
	public static final String TRASH_ICON = "GUI-ICON-TRASH-BUTTON";
	public static final String DELETE_ICON = "GUI-ICON-DELETE-BUTTON";
	public static final String VIEW_ICON = "GUI-ICON-VIEW-BUTTON";
	public static final String LOAD_ICON = "GUI-ICON-RELOAD-BUTTON";
	public static final String LOCKED_ICON = "GUI-ICON-LOCKED-BUTTON";
	public static final String UNLOCKED_ICON = "GUI-ICON-UNLOCKED-BUTTON";

	public static final String CONFIRM_ICON = "GUI-ICON-CONFIRM-BUTTON";
	public static final String CANCEL_ICON = "GUI-ICON-CANCEL-BUTTON";
	public static final String ADVANCED_ICON = "GUI-ICON-ADVANCED-BUTTON";
	public static final String PLAY_ICON = "GUI-ICON-PLAY-BUTTON";
	public static final String PAUSE_ICON = "GUI-ICON-PAUSE-BUTTON";
	public static final String WEB_ICON = "GUI-ICON-WEBREPORT-BUTTON";

	public static final String RETAILER_ICON = "GUI-ICON-RETAILER";
	public static final String WHOLESALER_ICON = "GUI-ICON-WHOLESALER";
	public static final String DISTRIBUTOR_ICON = "GUI-ICON-DISTRIBUTOR";
	public static final String PRODUCER_ICON = "GUI-ICON-PRODUCER";

	public static final String DEMAND_PARAMETER_SINGLESTEP_INIVAL = "DEMAND-PARAM-SINGLESTEP-INITIAL-VALUE";
	public static final String DEMAND_PARAMETER_SINGLESTEP_FINVAL = "DEMAND-PARAM-SINGLESTEP-FINAL-VALUE";
	public static final String DEMAND_PARAMETER_SINGLESTEP_STEPWEEK = "DEMAND-PARAM-SINGLESTEP-STEP-CHANGE-WEEK";
	public static final String DEMAND_PARAMETER_SINGLESTEP_FINWEEK = "DEMAND-PARAM-SINGLESTEP-FINAL-WEEK";

	public static final String DEMAND_TYPE_SINGLESTEP = "DEMAND-TYPE-SINGLESTEP";
	public static final String DEMAND_TYPE_UNKNOWN = "DEMAND-TYPE-UNKNOWN";

	public static final String SUPPLYCHAIN_TYPE_CLASSIC = "SUPPLYCHAIN-TYPE-CLASSIC";
	public static final String SUPPLYCHAIN_TYPE_UNKNOWN = "SUPPLYCHAIN-TYPE-UNKNOWN";

	public static final String DEFAULT_GAME_NAME = "DEFAULT-GAME-NAME";

        public static final String TITLE_REPORT_ORDER = "TITLE-REPORT-ORDER-TAB";
        public static final String TITLE_REPORT_STOCK = "TITLE-REPORT-STOCK-TAB";
	public static final String TITLE_REPORT_GENERAL = "TITLE-REPORT-GENERAL-TAB";
	public static final String TITLE_REPORT_RETAILER = "TITLE-REPORT-RETAILER-TAB";
	public static final String TITLE_REPORT_WHOLESALER = "TITLE-REPORT-WHOLESALER-TAB";
	public static final String TITLE_REPORT_DISTRIBUTOR = "TITLE-REPORT-DISTRIBUTOR-TAB";
	public static final String TITLE_REPORT_PRODUCER = "TITLE-REPORT-PRODUCER-TAB";
	public static final String TITLE_REPORT_UNKNOWN = "TITLE-REPORT-UNKNOWN-TAB";
        
        public static final String TOOLTIP_COMMON_IP = "TOOLTIP-COMMON-REFRESH-IP";
        public static final String TOOLTIP_COMMON_IP_INFO = "TOOLTIP-COMMON-IP-INFO";
        public static final String TOOLTIP_COMMON_LANG_BUTTON = "TOOLTIP-COMMON-LANGUAGE-CHANGE-BUTTON";
        public static final String TOOLTIP_COMMON_LANG_OPTION = "TOOLTIP-COMMON-LANGUAGE-CHANGE-OPTION";
        public static final String TOOLTIP_MAIN_HOME = "TOOLTIP-MAINSCENE-HOME-TAB";
        public static final String TOOLTIP_MAIN_CREATE = "TOOLTIP-MAINSCENE-CREATE-GAME-TAB";
        public static final String TOOLTIP_MAIN_GAME = "TOOLTIP-MAINSCENE-PLAY-GAME-TAB";
        public static final String TOOLTIP_MAIN_REPO = "TOOLTIP-MAINSCENE-SHOW-REPORT-TAB";
        public static final String TOOLTIP_GAME_COMP_LOAD_GAME = "TOOLTIP-GAME-COMPONENT-LOAD-GAME";
        public static final String TOOLTIP_GAME_COMP_LOAD_REPO = "TOOLTIP-GAME-COMPONENT-LOAD-REPORT";
        public static final String TOOLTIP_GAME_COMP_REMO_GAME = "TOOLTIP-GAME-COMPONENT-REMOVE-GAME";
        public static final String TOOLTIP_GAME_COMP_REMO_REPO = "TOOLTIP-GAME-COMPONENT-REMOVE-REPORT";
        public static final String TOOLTIP_CREA_GAME_INP_NAME = "TOOLTIP-CREATE-GAME-INPUT-NAME";
        public static final String TOOLTIP_CREA_GAME_INP_ISINFO = "TOOLTIP-CREATE-GAME-INPUT-INFORMED";
        public static final String TOOLTIP_CREA_GAME_INP_USEPASSW = "TOOLTIP-CREATE-GAME-INPUT-USE-PASSWORD";
        public static final String TOOLTIP_CREA_GAME_INP_PASSW = "TOOLTIP-CREATE-GAME-INPUT-PASSWORD";
        public static final String TOOLTIP_CREA_GAME_INP_DEM_CHOOSER = "TOOLTIP-CREATE-GAME-INPUT-DEMAND-TYPE-CHOOSER";
        public static final String TOOLTIP_CREA_GAME_INP_DEM_SS_INITVAL = "TOOLTIP-CREATE-GAME-INPUT-DEMAND-TYPE-SINGLESTEP-INITIAL-VALUE";
        public static final String TOOLTIP_CREA_GAME_INP_DEM_SS_FINALVAL = "TOOLTIP-CREATE-GAME-INPUT-DEMAND-TYPE-SINGLESTEP-FINAL-VALUE";
        public static final String TOOLTIP_CREA_GAME_INP_DEM_SS_STEPWEEK = "TOOLTIP-CREATE-GAME-INPUT-DEMAND-TYPE-SINGLESTEP-STEP-WEEK";
        public static final String TOOLTIP_CREA_GAME_INP_DEM_CHART = "TOOLTIP-CREATE-GAME-INPUT-DEMAND-TYPE-PREVIEW-CHART";
        public static final String TOOLTIP_CREA_GAME_INP_MISSC = "TOOLTIP-CREATE-GAME-INPUT-COST-MISSING";
        public static final String TOOLTIP_CREA_GAME_INP_STOCKC = "TOOLTIP-CREATE-GAME-INPUT-COST-STOCKING";
        public static final String TOOLTIP_CREA_GAME_INP_SELLP = "TOOLTIP-CREATE-GAME-INPUT-PROFIT-SELLING";
        public static final String TOOLTIP_CREA_GAME_INP_REAL_DUR = "TOOLTIP-CREATE-GAME-INPUT-REAL-DURATION";
        public static final String TOOLTIP_CREA_GAME_INP_INF_DUR = "TOOLTIP-CREATE-GAME-INPUT-INFORMED-DURATION";
        public static final String TOOLTIP_CREA_GAME_INP_DELI_DELAY = "TOOLTIP-CREATE-GAME-INPUT-DELIVERY-DELAY";
        public static final String TOOLTIP_CREA_GAME_INP_START_STOCK = "TOOLTIP-CREATE-GAME-INPUT-STARTING-STOCK";
        public static final String TOOLTIP_CREA_GAME_INP_SCHAIN_CHOOSER = "TOOLTIP-CREATE-GAME-INPUT-SUPPLYCHAIN-CHOOSER";
        public static final String TOOLTIP_CREA_GAME_BUTTON_SACCEP = "TOOLTIP-CREATE-GAME-BUTTON-SIMPLE-ACCEPT";
        public static final String TOOLTIP_CREA_GAME_BUTTON_SCLEAR = "TOOLTIP-CREATE-GAME-BUTTON-SIMPLE-CLEAR";
        public static final String TOOLTIP_CREA_GAME_BUTTON_SADVAN = "TOOLTIP-CREATE-GAME-BUTTON-SIMPLE-ADVANCED";
        public static final String TOOLTIP_CREA_GAME_BUTTON_AACCEP = "TOOLTIP-CREATE-GAME-BUTTON-ADVANCED-ACCEPT";
        public static final String TOOLTIP_CREA_GAME_BUTTON_ACLEAR = "TOOLTIP-CREATE-GAME-BUTTON-ADVANCED-CLEAR";
        public static final String TOOLTIP_PLAY_GAME_INFO = "TOOLTIP-PLAY-GAME-INFORMATION";
        public static final String TOOLTIP_PLAY_GAME_BUTTON_START = "TOOLTIP-PLAY-GAME-START-BUTTON";
        public static final String TOOLTIP_PLAY_GAME_BUTTON_PAUSE = "TOOLTIP-PLAY-GAME-PAUSE-BUTTON";
        public static final String TOOLTIP_PLAY_GAME_PL_POOL = "TOOLTIP-PLAY-GAME-PLAYERS-POOL";
        public static final String TOOLTIP_PLAY_GAME_POSIT_BEGIN = "TOOLTIP-PLAY-GAME-PLAYERS-PLAYER-POSITIONER-BEGIN";
        public static final String TOOLTIP_PLAY_GAME_POSIT_END = "TOOLTIP-PLAY-GAME-PLAYERS-PLAYER-POSITIONER-END";
        public static final String TOOLTIP_PLAY_GAME_LOCKUN_BEGIN = "TOOLTIP-PLAY-GAME-PLAYERS-PLAYER-LOCK-UNLOCK-BEGIN";
        public static final String TOOLTIP_PLAY_GAME_LOCKUN_END = "TOOLTIP-PLAY-GAME-PLAYERS-PLAYER-LOCK-UNLOCK-END";
        public static final String TOOLTIP_SHOW_REPO_INFO = "TOOLTIP-SHOW-REPORT-INFORMATION";
        public static final String TOOLTIP_SHOW_REPO_BUTT_START = "TOOLTIP-SHOW-REPORT-START-BUTTON";
        public static final String TOOLTIP_SHOW_REPO_BUTT_PAUSE = "TOOLTIP-SHOW-REPORT-PAUSE-BUTTON";
        public static final String TOOLTIP_SHOW_REPO_TAB_ORDER = "TOOLTIP-SHOW-REPORT-ORDER-TAB";
        public static final String TOOLTIP_SHOW_REPO_TAB_STOCK = "TOOLTIP-SHOW-REPORT-STOCK-TAB";
        
        public static String LABEL_INFO_STATUS = "GUI-LABEL-INFORMATION-GAME-STATUS";
        public static String TEXT_IP_BEGIN = "IP-TEXT-BEGIN";
        public static String TEXT_IP_MIDDLE_ERROR = "IP-TEXT-MIDDLE-IP-ERROR";
        public static String TEXT_IP_MIDDLE = "IP-TEXT-MIDDLE-DOTS";
        public static String TEXT_IP_END = "IP-TEXT-END";
        public static String INFO_NO_PASSW = "INFORMATION-NO-PASSWORD";
        public static String INFO_IS_GAME = "INFORMATION-IS-GAME";
        public static String INFO_IS_REPORT = "INFORMATION-IS-REPORT";
        public static String INFO_IS_INFORMED = "INFORMATION-IS-INFOMED-SUPPLYCHAIN";
        public static String INFO_NOT_INFORMED = "INFORMATION-NOT-INFOMED-SUPPLYCHAIN";
        
        public static String CHART_OR_TITLE = "CHART-ORDER-TITLE";
        public static String CHART_OR_LABEL_X = "CHART-ORDER-LABEL-X-AXIS";
        public static String CHART_OR_LABEL_Y = "CHART-ORDER-LABEL-Y-AXIS";
        public static String CHART_OR_FUNCTION_AX = "CHART-ORDER-FUNCTION-";
        public static String CHART_OR_FUNCTION_0 = "CHART-ORDER-FUNCTION-0";
        public static String CHART_OR_FUNCTION_1 = "CHART-ORDER-FUNCTION-1";
        public static String CHART_OR_FUNCTION_2 = "CHART-ORDER-FUNCTION-2";
        public static String CHART_OR_FUNCTION_3 = "CHART-ORDER-FUNCTION-3";
        public static String CHART_OR_FUNCTION_4 = "CHART-ORDER-FUNCTION-4";
        
        public static String CHART_ST_TITLE = "CHART-STOCK-TITLE";
        public static String CHART_ST_LABEL_X = "CHART-STOCK-LABEL-X-AXIS";
        public static String CHART_ST_LABEL_Y = "CHART-STOCK-LABEL-Y-AXIS";
        public static String CHART_ST_FUNCTION_AX = "CHART-STOCK-FUNCTION-";
        public static String CHART_ST_FUNCTION_0 = "CHART-STOCK-FUNCTION-0";
        public static String CHART_ST_FUNCTION_1 = "CHART-STOCK-FUNCTION-1";
        public static String CHART_ST_FUNCTION_2 = "CHART-STOCK-FUNCTION-2";
        public static String CHART_ST_FUNCTION_3 = "CHART-STOCK-FUNCTION-3";
        public static String CHART_ST_FUNCTION_4 = "CHART-STOCK-FUNCTION-4";
}
