/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.utfpr.ct.localization;

/**
 *
 * @author henrique
 */
public class LocalizationKeys {
    public static final String FRAME_NAME = "GUI-FRAME-NAME";
    
    public static String LABEL_STARTING_WAIT = "GUI-LABEL-AWAIT-START";
    public static String LABEL_CREATEGAME_NAME = "GUI-LABEL-CREATEGAME-NAME";
    public static String LABEL_CREATEGAME_PASSWORD_FIELD = "GUI-LABEL-CREATEGAME-PASSWORD-FIELD";
    public static String LABEL_CREATEGAME_PASSWORD_CHECK = "GUI-LABEL-CREATEGAME-PASSWORD-CHECK";
    public static String LABEL_CREATEGAME_MISSINGUC = "GUI-LABEL-CREATEGAME-MISSING-UNIT-COST";
    public static String LABEL_CREATEGAME_STOCKUC = "GUI-LABEL-CREATEGAME-STOCK-UNIT-COST";
    public static String LABEL_CREATEGAME_SELLINGP = "GUI-LABEL-CREATEGAME-SELLING-PROFFIT";
    public static String LABEL_CREATEGAME_REAL_DURATION = "GUI-LABEL-CREATEGAME-REAL-DURATION";
    public static String LABEL_CREATEGAME_INF_DURATION = "GUI-LABEL-CREATEGAME-INFORMED-DURATION";
    public static String LABEL_CREATEGAME_DEMAND = "GUI-LABEL-CREATEGAME-DEMAND";
    public static String LABEL_CREATEGAME_INFORMED_SC = "GUI-LABEL-CREATEGAME-INFORMED_SUPPLYCHAIN";
    public static String LABEL_CREATEGAME_DELIVERY_DELAY = "GUI-LABEL-CREATEGAME-DELIVERY-DELAY";
    public static String LABEL_CREATEGAME_INITIAL_STOCK = "GUI-LABEL-CREATEGAME-INITIAL-STOCK";
    
    public static String TITLE_CREATEGAME_SECURITY_BORDER = "GUI-TITLE-CREATEGAME-SECURITY-BORDER";
    public static String TITLE_CREATEGAME_DEMAND_BORDER = "GUI-TITLE-CREATEGAME-DEMAND-BORDER";
    public static String TITLE_CREATEGAME_COSTS_BORDER = "GUI-TITLE-CREATEGAME-COSTS-BORDER";
    public static String TITLE_CREATEGAME_DURATION_BORDER = "GUI-TITLE-CREATEGAME-DURATION-BORDER";
    public static String TITLE_CREATEGAME_SUPPLYCHAIN_BORDER = "GUI-TITLE-CREATEGAME-SUPPLYCHAIN-BORDER";
    
    public static String MESSAGE_CREATEGAME_WARN_TITLE = "GUI-WARNING-CREATEGAME-FAILED";
    public static String MESSAGE_CREATEGAME_WARN_FAIL = "GUI-WARNING-CREATEGAME-FAILED-TITLE";
    
    public static String HOME_ICON = "GUI-ICON-HOME-TAB";
    public static String PLUS_ICON = "GUI-ICON-PLUS-TAB";
    public static String RELOAD_ICON = "GUI-ICON-RELOAD-BUTTON";
    public static String TRASH_ICON = "GUI-ICON-DELETE-BUTTON";
    
    public static String CONFIRM_ICON = "GUI-ICON-CONFIRM-BUTTON";
    public static String CANCEL_ICON = "GUI-ICON-CANCEL-BUTTON";
    
    public static String RETAILER_ICON = "GUI-ICON-RETAILER";
    public static String WHOLESALER_ICON = "GUI-ICON-WHOLESALER";
    public static String DISTRIBUTOR_ICON = "GUI-ICON-DISTRIBUTOR";
    public static String PRODUCER_ICON = "GUI-ICON-PRODUCER";
    
    public static String DEMAND_PARAMETER_SINGLESTEP_INIVAL = "DEMAND-PARAM-SINGLESTEP-INITIAL-VALUE";
    public static String DEMAND_PARAMETER_SINGLESTEP_FINVAL = "DEMAND-PARAM-SINGLESTEP-FINAL-VALUE";
    public static String DEMAND_PARAMETER_SINGLESTEP_STEPWEEK = "DEMAND-PARAM-SINGLESTEP-STEP-CHANGE-WEEK";
    public static String DEMAND_PARAMETER_SINGLESTEP_FINWEEK = "DEMAND-PARAM-SINGLESTEP-FINAL-WEEK";
    
    public static String DEMAND_TYPE_SINGLESTEP = "DEMAND-TYPE-SINGLESTEP";
    
    public static String SUPPLYCHAIN_TYPE_CLASSIC = "SUPPLYCHAIN-TYPE-CLASSIC";
    
    public static String DEFAULT_GAME_NAME = "DEFAULT-GAME-NAME";
}
